### ISSUE TITLE
Visualizzare percentuali come % e non come frazioni di 1

### ISSUE THREAD

**Issue by vi-enne** [gabrielepinto/dati_simulatore_elettorale#2]
Potrebbe essere più intuitivo visualizzare le percentuali appunto come % (su 100) e non come frazioni di 1.
Al momento a uno sguardo veloce sembra che, ad esempio, FdI abbia lo 0.242% e non il 24.2%.
![image](https://user-images.githubusercontent.com/44818674/187943988-845e0beb-7bac-4ecd-9eee-5246638a83c1.png)

**Comment by gabrielepinto** [comment]
ok fatto! :)

**Comment by vi-enne** [comment]
Grazie!
